version: '3'
services:
  # ref: https://github.com/nacos-group/nacos-docker
  # ref: https://github.com/alibaba/nacos
  # 运行前需要执行mysql脚本,修改数据库地址，另外可以通过custom.properties自定义nacos
  #  数据库采用dnmp的数据库，无需再安装mysql 。新建nacos数据库，执行SQL脚本初始化数据库。
  #  MySQL 文件：
  #  https://github.com/Gleans/SpringCloudPro/blob/master/docker/mysql-init/init.sql
  # 测试13
  nacos:
    image: nacos/nacos-server:1.4.1
    container_name: nacos
    hostname: nacos
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_SERVICE_HOST=mysql5
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - NACOS_AUTH_ENABLE=false
    volumes:
      - ./service/nacos/data/docker_file/naocs/logs:/home/nacos/logs
    expose:
      - "8848"
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always

